### ISSUE TITLE
GCC 11.3 without -Wno-array-parameter

### ISSUE THREAD

**Issue by andreiw** [intel/MultiArchUefiPkg#21]
Rebecca Cran reports -Wno-array-parameter had to be added to CC flags for efi/UnicornX86Lib.inf to build with GCC 11.3 targeting AArch64

**Comment by andreiw** [comment]
This is mildly strange as I didn't see any issues building with GCC-12 or GCC-13 (but targeting RISC-V).

**Comment by ghost** [comment]
When I build with `build -p MultiArchUefiPkg/Emulator.dsc -a AARCH64 -t GCC` with gcc 12.2.0 I get the following error:
```
In file included from /home/bcran/src/tianocore/edk2/unicorn/qemu/tcg/tcg.c:294:
/home/bcran/src/tianocore/edk2/unicorn/qemu/tcg/aarch64/tcg-target.inc.c:1860:37: error: argument 3 of type ‘const TCGArg[16]’ {aka ‘const long long unsigned int[16]’} with mismatched bound [-Werror=array-parameter=]
 1860 |                        const TCGArg args[TCG_MAX_OP_ARGS],
      |                        ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/bcran/src/tianocore/edk2/unicorn/qemu/tcg/tcg.c:110:68: note: previously declared as ‘const TCGArg *’ {aka ‘const long long unsigned int *’}
  110 | static void tcg_out_op(TCGContext *s, TCGOpcode opc, const TCGArg *args,
      |                                                      ~~~~~~~~~~~~~~^~~~
/home/bcran/src/tianocore/edk2/unicorn/qemu/tcg/aarch64/tcg-target.inc.c:1861:34: error: argument 4 of type ‘const int[16]’ with mismatched bound [-Werror=array-parameter=]
 1861 |                        const int const_args[TCG_MAX_OP_ARGS])
      |                        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bcran/src/tianocore/edk2/unicorn/qemu/tcg/tcg.c:111:35: note: previously declared as ‘const int *’
  111 |                        const int *const_args);
      |                        ~~~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [GNUmakefile:392: /home/bcran/src/tianocore/edk2/Build/MultiArchUefiPkg/DEBUG_GCC/AARCH64/unicorn/efi/UnicornX86Lib/OUTPUT/qemu/tcg/tcg.obj] Error 1
```
